### ISSUE TITLE
Docker build automatically check for new remote changes

### ISSUE THREAD

**Issue by ChristianHinge** [CAAI/rh-library#1]
If the Dockerfile uses something like:

`RUN git clone https://github.com/CAAI/my_repo`

then docker might skip this line and use the cached result instead.  This is problematic if new commits have been made to the repo.

**Comment by claesnl** [comment]
Indeed this fixed it. I've updated the README on rh-node branch with this detail. See https://github.com/CAAI/rh-node/commit/b8762bedce23a97e004b91cc8ff1f1ae76cf542d
